### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [ryderclayton/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by ryderclayton** [comment]
Hi Bill,

Thank you for the feedback! I want to know how to make things better.  

I am still new to Github and updating the app.  Are you asking for me to just post the solution in the comments section? Or to actually update the application and push it to Github?  

I think I figured out how to fix the issue.  Would you add <meta name=viewport content = “width=device-width, initial-scale=1”> to head of the application.html.erb file?

Best,
Ryder

**Comment by BillyMassey** [comment]
Update your code and push it live! You should be able to see a difference
on mobile.

Afterwards, let me know here in the comments and I'll take a quick look.
And to your last question: you are correct :)

**Comment by ryderclayton** [comment]
Hi Bill,

I updated my code and pushed it to Heroku, but it didn't change.  Here is a screenshot of the code I added.  Am I missing something?

<img width="829" alt="screen shot 2016-08-04 at 7 54 52 am" src="https://cloud.githubusercontent.com/assets/20451571/17406618/0b35d00c-5a19-11e6-8b15-a6429d1f3782.png">

**Comment by BillyMassey** [comment]
Hi Ryder -

The types of quotation marks you used are a bit different.  Why don’t you remove what you added and retype it by hand vs. copying and pasting.  So instead of:

  <meta name=viewport content = “width=device-width, initial-scale=1”>

It should be:

  <meta name=viewport content = "width=device-width, initial-scale=1">

The character “ is slightly different than the character “ and a web browser views them differently.

Cheers,
Billy

**Comment by ryderclayton** [comment]
I feel like a dope! I should've noticed that. The mobile version looks much better now. Do you mind reviewing it just to double check?  

Thank you for your help, Billy!
Ryder

**Comment by BillyMassey** [comment]
No sweat! It's all part of the process :)

Good Job Ryder! 👍
